// This file was generated by Prisma
import { defineConfig } from "prisma/config";

// Supabase compatible configuration
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
